#!/usr/bin/env zsh
# bootstrap-mac.sh — set up a brand-new Mac from zero.
# Generated by generate-bootstrap.sh.  Re-run that script to refresh this file
# whenever you add or remove Homebrew packages.
# Generated on 2026-06-10 by josh@joshair
# joshconfig-bootstrap version: 0.3.0
set -euo pipefail

echo "joshconfig-bootstrap v0.3.0 — generated by josh@joshair"
echo "==> target: $(uname -m) / $(sw_vers -productName 2>/dev/null || echo macOS) $(sw_vers -productVersion 2>/dev/null || echo unknown)"
echo ""

echo "=== Step 1: enable passwordless sudo ==="
if [[ -f /etc/sudoers.d/nopasswd ]]; then
  echo "Already present: /etc/sudoers.d/nopasswd"
else
  echo "Writing /etc/sudoers.d/nopasswd (you will be prompted for your password once) …"
  sudo tee /etc/sudoers.d/nopasswd >/dev/null <<'SUDOERS'
root		ALL = (ALL) NOPASSWD: ALL
%admin		ALL = (ALL) NOPASSWD: ALL
SUDOERS
  sudo chmod 0440 /etc/sudoers.d/nopasswd
fi

echo "=== Step 2: Xcode Command Line Tools ==="
if xcode-select -p &>/dev/null; then
  echo "Already installed: $(xcode-select -p)"
else
  echo "Starting install (this opens a GUI dialog) …"
  xcode-select --install
  echo "Press any key once the install finishes."
  read -r _
fi

echo "=== Step 3: Homebrew ==="

if command -v brew &>/dev/null; then
  echo "Homebrew already installed: $(brew --version | head -1)"
else
  echo "Downloading & installing Homebrew …"
  # The shell-script installer is the canonical, version-agnostic method.
  /bin/bash -c \
    "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  # If you prefer an Apple-signed .pkg for MDM / air-gapped deployments,
  # swap the block above with the URL for the release you need, e.g.:
  #   curl -fsSLO https://github.com/Homebrew/brew/releases/download/5.1.15/Homebrew.pkg
  #   sudo installer -pkg Homebrew.pkg -target /

  # Ensure brew is on PATH for the rest of this script.
  if [[ -x /opt/homebrew/bin/brew ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
  elif [[ -x /usr/local/bin/brew ]]; then
    eval "$(/usr/local/bin/brew shellenv)"
  fi
fi

# Detect macOS beta: build versions ending in a letter (e.g. 24A526j).
BUILD="$(sw_vers -buildVersion 2>/dev/null || true)"
if [[ -n "$BUILD" && "$BUILD" =~ [a-zA-Z]$ ]]; then
  echo "macOS beta detected (build $BUILD) — enabling Homebrew developer mode"
  brew developer on
fi

# ---- generated packages below ----

echo '=== Step 4: Homebrew formulas ==='
brew install \
  bun \
  ffmpeg \
  ffmpeg-full \
  fzf \
  gh \
  gnupg \
  go \
  gopls \
  imagesnap \
  nasm \
  neovim \
  pinentry-mac \
  pyright \
  ripgrep \
  ruff \
  rust \
  tree-sitter-cli \
  ty \
  uv \
  yaml-language-server

echo '=== Step 5: Homebrew casks ==='
brew install --cask \
  bitwarden \
  codexbar \
  github

echo '=== Step 6: joshconfig ==='
JOSHRC="$HOME/src/joshrodd/joshconfig"
if [[ -d "$JOSHRC" ]]; then
  echo "joshconfig repo exists — pulling latest …"
  git -C "$JOSHRC" pull --ff-only
else
  echo "Cloning joshconfig …"
  mkdir -p "$(dirname "$JOSHRC")"
  git clone https://github.com/JoshRodd/joshconfig.git "$JOSHRC"
fi
echo "Building joshconfig …"
cargo build --release --bins --manifest-path "$JOSHRC/Cargo.toml"
"$JOSHRC/scripts/install.sh"

# Add loader to .zshrc if not already present.
LOADER_LINE='. "$HOME/.local/bin/joshconfig-load-paths.sh"'
if ! grep -qF "$LOADER_LINE" "$HOME/.zshrc" 2>/dev/null; then
  echo "Appending loader to ~/.zshrc …"
  echo "$LOADER_LINE" >> "$HOME/.zshrc"
else
  echo "Loader already in ~/.zshrc"
fi

echo '=== Step 7: bun global packages ==='
if command -v bun &>/dev/null; then
  echo "bun already installed: $(bun --version)"
else
  echo "bun not found — install it via brew first, then re-run this script."
  exit 1
fi

bun install -g @oh-my-pi/pi-coding-agent

echo '=== Step 8: trust untrusted bun dependencies ==='
bun pm -g trust onnxruntime-node protobufjs sharp

# Verify nothing is left untrusted.
UNTRUSTED="$(bun pm -g trust --list 2>/dev/null || true)"
if [[ -n "$UNTRUSTED" ]]; then
  echo "WARNING: untrusted packages remain:"
  echo "$UNTRUSTED"
  echo "Run 'bun pm -g trust <pkg>' for each."
else
  echo "All bun packages trusted."
fi
