#!/usr/bin/env zsh
# generate-bootstrap.sh — query this Mac's Homebrew state and produce a
# bootstrap-mac.sh script you can carry to a brand-new machine.
set -euo pipefail

OUTFILE="${1:-bootstrap-mac.sh}"

command -v brew >/dev/null 2>&1 || {
  echo "ERROR: Homebrew not found. Run this on a Mac that already has brew installed." >&2
  exit 1
}

FORMULAS=("${(@f)$(brew leaves | sort)}")
CASKS=("${(@f)$(brew list --cask 2>/dev/null | sort || true)}")
TAP_OUT="$(brew tap 2>/dev/null | sort || true)"
TAPS=()
if [[ -n "$TAP_OUT" ]]; then
  TAPS=("${(@f)TAP_OUT}")
fi

cat >"$OUTFILE" <<'HEADER'
#!/usr/bin/env zsh
# bootstrap-mac.sh — set up a brand-new Mac from zero.
# Generated by generate-bootstrap.sh.  Re-run that script to refresh this file
# whenever you add or remove Homebrew packages.
set -euo pipefail

echo "=== Step 1: Xcode Command Line Tools ==="
if xcode-select -p &>/dev/null; then
  echo "Already installed: $(xcode-select -p)"
else
  echo "Starting install (this opens a GUI dialog) …"
  xcode-select --install
  echo "Press any key once the install finishes."
  read -r _
fi

echo "=== Step 2: Homebrew ==="
if command -v brew &>/dev/null; then
  echo "Homebrew already installed: $(brew --version | head -1)"
else
  echo "Downloading & installing Homebrew …"
  # The shell-script installer is the canonical, version-agnostic method.
  /bin/bash -c \
    "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  # If you prefer an Apple-signed .pkg for MDM / air-gapped deployments,
  # swap the block above with the URL for the release you need, e.g.:
  #   curl -fsSLO https://github.com/Homebrew/brew/releases/download/5.1.15/Homebrew.pkg
  #   sudo installer -pkg Homebrew.pkg -target /

  # Ensure brew is on PATH for the rest of this script.
  if [[ -x /opt/homebrew/bin/brew ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
  elif [[ -x /usr/local/bin/brew ]]; then
    eval "$(/usr/local/bin/brew shellenv)"
  fi
fi

# ---- generated packages below ----
HEADER

STEP=3

# Emit formulas
if (( ${#FORMULAS} > 0 )); then
  {
    echo ""
    echo "echo '=== Step $STEP: Homebrew formulas ==='"
    echo "brew install \\"
    for ((i = 1; i < ${#FORMULAS}; i++)); do
      echo "  ${FORMULAS[i]} \\"
    done
    echo "  ${FORMULAS[-1]}"
  } >>"$OUTFILE"
  ((STEP++))
fi

# Emit casks
if (( ${#CASKS} > 0 )); then
  {
    echo ""
    echo "echo '=== Step $STEP: Homebrew casks ==='"
    echo "brew install --cask \\"
    for ((i = 1; i < ${#CASKS}; i++)); do
      echo "  ${CASKS[i]} \\"
    done
    echo "  ${CASKS[-1]}"
  } >>"$OUTFILE"
  ((STEP++))
fi

# Emit taps (if any)
if (( ${#TAPS} > 0 )); then
  {
    echo ""
    echo "echo '=== Step $STEP: Homebrew taps ==='"
    for tap in "${TAPS[@]}"; do
      echo "brew tap $tap"
    done
  } >>"$OUTFILE"
  ((STEP++))
fi

# Emit bun global packages
{
  echo ""
  echo "echo '=== Step $STEP: bun global packages ==='"
  echo 'if command -v bun &>/dev/null; then'
  echo '  echo "bun already installed: $(bun --version)"'
  echo 'else'
  echo '  echo "bun not found — install it via brew first, then re-run this script."'
  echo '  exit 1'
  echo 'fi'
  echo ""
  echo "bun install -g @oh-my-pi/pi-coding-agent"
  ((STEP++))
} >>"$OUTFILE"

{
  echo ""
  echo "echo '=== Step $STEP: trust untrusted bun dependencies ==='"
  echo "bun pm -g trust onnxruntime-node protobufjs sharp"
  echo ""
  echo "# Verify nothing is left untrusted."
  echo 'UNTRUSTED="$(bun pm -g trust --list 2>/dev/null || true)"'
  echo 'if [[ -n "$UNTRUSTED" ]]; then'
  echo '  echo "WARNING: untrusted packages remain:"'
  echo '  echo "$UNTRUSTED"'
  echo "  echo \"Run 'bun pm -g trust <pkg>' for each.\""
  echo 'else'
  echo '  echo "All bun packages trusted."'
  echo 'fi'
} >>"$OUTFILE"

chmod +x "$OUTFILE"
echo "Wrote $OUTFILE ($(wc -l <"$OUTFILE") lines)"
